
# The initial account created at start-up if an account
# with the same handle doesn't already exist. This account
# will have admin privileges.
InitHandle = "admin"
InitEmail = "example@domain.com"
InitPass = "password"

# Email settings.
EmailHost = "smtp.domain.com"
EmailPort = "587"
EmailUser = "apikey"
EmailPass = "your_api_key_here"
EmailFrom = "support@storydevs.com"
EmailName = "StoryDevs"

# Provide a connection string to your local postgres database.
# Substitute values for your own except sslmode=disable
DbConn = "user=postgres dbname=postgres password=pw sslmode=disable"
