name: Go
on: [push, pull_request]
jobs:

  linux:
    name: Go ${{ matrix.go }} on Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.16']
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Get Go dependencies
      run: |
        export GO111MODULE=on
        go mod download
        go get -v

    - name: Build
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin
        go build -v ./...

  windows:
      runs-on: windows-latest
      strategy:
        matrix:
          go: ['1.16']
      name: Go ${{ matrix.go }} on Windows
      steps:
        - name: Check out code into the Go module directory
          uses: actions/checkout@v1

        - name: Setup Go
          uses: actions/setup-go@v1
          with:
            go-version: ${{ matrix.go }}

        - name: Get Go dependencies
          run: |
            echo %USERPROFILE%\go\bin >> %GITHUB_PATH%
            go mod download
            go get -v

        - name: Build
          run: |
            go build -v ./...

  macos:
      runs-on: macOS-latest
      strategy:
        matrix:
          go: ['1.16']
      name: Go ${{ matrix.go }} on MacOS
      steps:
        - name: Check out code into the Go module directory
          uses: actions/checkout@v1

        - name: Setup Go
          uses: actions/setup-go@v1
          with:
            go-version: ${{ matrix.go }}

        - name: Get Go dependencies
          run: |
            echo $HOME/go/bin >> %GITHUB_PATH%
            go mod download
            go get -v

        - name: Build
          run: |
            go build -v ./...
